
networks:
    traefik:
        external: true
    
services:
    traefik:
        image: traefik:v3.5.0
        container_name: traefik
        restart: always
        ports:
            - "80:80"
            - "8080:8080"
            - "443:443"
            - "25:25"
            - "465:465"
            - "993:993"
        command:
            - "--api.dashboard=true"  # Enable dashboard
            - "--api.insecure=true"  # Enable insecure mode      
            - --providers.docker=true
            - --providers.file.filename=/etc/traefik/dynamic_conf.yml
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
            - --entrypoints.web.http.redirections.entryPoint.to=websecure
            - --entrypoints.web.http.redirections.entryPoint.scheme=https
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./certificates:/etc/traefik/certs:ro
            - ./dynamic_conf.yml:/etc/traefik/dynamic_conf.yml:ro
        networks:
            - traefik
      
