networks:
    traefik:
        external: true
    
services:
    whoami:
        image: traefik/whoami
        labels:
            - traefik.http.routers.whoami.rule=Host(`who.landingdev.xyz`)
            - traefik.http.routers.whoami.entrypoints=websecure
            - traefik.http.routers.whoami.tls=true
        networks:
            - traefik
  
